server:
  port: 8550
eureka:  instance:    hostname: 127.0.0.1
  client:
    service-url:      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: train-edu-eureka-server
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false